config/routes.rb
Rails.application.routes.draw do
  resources :playlists

  resources :groups

  resources :guests do
    get 'template/:id' => 'guests#template'      
  end

  resources :cci do
    
  end

  resources :comments

  resources :movies

  resources :managers

  resources :plays

  resources :song do
    get 'template/:id' => 'song#template'
  end

  get 'wsi' => 'cci#wsi'  
  get '/' => 'song#index', as: 'music'
  get 'sam' => 'song#home'
  get 's' => 'song#download'
  get 'search/:term' => 'song#search'

  get 'dl/:name' => 'song#send_zip', as: 'download_zip'
  get 'ds/:id' => 'song#send_song', as: 'download_song'
  post 'q.json' => 'song#add_to_session_playlist', as: 'add_to_playlist'
  get 'reset' => 'song#clear', as: 'reset'
  post 'remove.json' => 'song#add_to_session_filter', as: 'remove'
  get 'm' => 'song#mobile', as: 'mobile'

  get 'guest_search/:name' => 'guests#find_by_name'
  get 'random/:count' => 'song#random'      
  get 'media/:mediaid' => 'song#mediaid'
  get 'code' => 'code#index'

end

app/models/play.rb
class Play < ActiveRecord::Base
  belongs_to :song
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:create]


  # GET /plays
  # GET /plays.json
  def index
    @plays = Play.all
  end

  # GET /plays/1
  # GET /plays/1.json
  def show
  end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit
  end

  # POST /plays
  # POST /plays.json
  def create
    @play = Play.new(play_params)

    respond_to do |format|
      if @play.save
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render :show, status: :created, location: @play }
      else
        format.html { render :new }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1
  # PATCH/PUT /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to @play, notice: 'Play was successfully updated.' }
        format.json { render :show, status: :ok, location: @play }
      else
        format.html { render :edit }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plays/1
  # DELETE /plays/1.json
  def destroy
    @play.destroy
    respond_to do |format|
      format.html { redirect_to plays_url, notice: 'Play was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_play
      @play = Play.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
      params.require(:play).permit(:song_id, :user_id, :lat, :long)
    end
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/plays/_form.html.erb
<%= form_for(@play) do |f| %>
  <% if @play.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@play.errors.count, "error") %> prohibited this play from being saved:</h2>

      <ul>
      <% @play.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :song_id %><br>
    <%= f.text_field :song_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plays/edit.html.erb
<h1>Editing play</h1>

<%= render 'form' %>

<%= link_to 'Show', @play %> |
<%= link_to 'Back', plays_path %>

app/views/plays/index.html.erb
<h1>Listing plays</h1>

<table>
  <thead>
    <tr>
      <th>Song</th>
      <th>User</th>
      <th>Lat</th>
      <th>Long</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plays.each do |play| %>
      <tr>
        <td><%= play.song_id %></td>
        <td><%= play.user_id %></td>
        <td><%= play.lat %></td>
        <td><%= play.long %></td>
        <td><%= link_to 'Show', play %></td>
        <td><%= link_to 'Edit', edit_play_path(play) %></td>
        <td><%= link_to 'Destroy', play, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Play', new_play_path %>

app/views/plays/new.html.erb
<h1>New play</h1>

<%= render 'form' %>

<%= link_to 'Back', plays_path %>

app/views/plays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song:</strong>
  <%= @play.song_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @play.user_id %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @play.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @play.long %>
</p>

<%= link_to 'Edit', edit_play_path(@play) %> |
<%= link_to 'Back', plays_path %>