config/routes.rb
Rails.application.routes.draw do
  resources :playlists

  resources :groups

  resources :guests do
    get 'template/:id' => 'guests#template'      
  end

  resources :cci do
    
  end

  resources :comments

  resources :movies

  resources :managers

  resources :plays

  resources :song do
    get 'template/:id' => 'song#template'
  end

  get 'wsi' => 'cci#wsi'  
  get '/' => 'song#index', as: 'music'
  get 'sam' => 'song#home'
  get 's' => 'song#download'
  get 'search/:term' => 'song#search'

  get 'dl/:name' => 'song#send_zip', as: 'download_zip'
  get 'ds/:id' => 'song#send_song', as: 'download_song'
  post 'q.json' => 'song#add_to_session_playlist', as: 'add_to_playlist'
  get 'reset' => 'song#clear', as: 'reset'
  post 'remove.json' => 'song#add_to_session_filter', as: 'remove'
  get 'm' => 'song#mobile', as: 'mobile'

  get 'guest_search/:name' => 'guests#find_by_name'
  get 'random/:count' => 'song#random'      
  get 'media/:mediaid' => 'song#mediaid'
  get 'code' => 'code#index'

end

app/models/manager.rb
class Manager < ActiveRecord::Base
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:paypal_id, :venmo_id, :square_id, :name)
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= form_for(@manager) do |f| %>
  <% if @manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% @manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paypal_id %><br>
    <%= f.text_field :paypal_id %>
  </div>
  <div class="field">
    <%= f.label :venmo_id %><br>
    <%= f.text_field :venmo_id %>
  </div>
  <div class="field">
    <%= f.label :square_id %><br>
    <%= f.text_field :square_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<h1>Listing managers</h1>

<table>
  <thead>
    <tr>
      <th>Paypal</th>
      <th>Venmo</th>
      <th>Square</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.paypal_id %></td>
        <td><%= manager.venmo_id %></td>
        <td><%= manager.square_id %></td>
        <td><%= manager.name %></td>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager', new_manager_path %>

app/views/managers/new.html.erb
<h1>New manager</h1>

<%= render 'form' %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paypal:</strong>
  <%= @manager.paypal_id %>
</p>

<p>
  <strong>Venmo:</strong>
  <%= @manager.venmo_id %>
</p>

<p>
  <strong>Square:</strong>
  <%= @manager.square_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @manager.name %>
</p>

<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>